name: Build Upon Trigger

on:
  repository_dispatch:
    types: [ trigger-build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Access data from Repo A (optional)
      run: |
        echo "Build type: ${{ github.event.client_payload.build_type }}"
        echo "Triggered from branch: ${{ github.event.client_payload.branch_name }}"

    - name: BuildA
      if: ${{ github.event.client_payload.build_type == 'unit-tests' }}
      # Specific steps for unit tests
      run: |
        echo "Running unit tests..."
        # Add your unit test commands here

    - name: BuildB
      if: ${{ github.event.client_payload.build_type != 'unit-tests' }}
      # Specific steps for other build types
      run: |
        echo "Running different build steps..."
        # Add your other build commands here

    - name: Build Successful
      run: echo "Build Successful!"
      if: always()
